language: node_js
node_js:
- '8'
env:
  global:
  - secure: MTqezURydr5oT71TDvaKCRUE6qNMYTFOdRyLsCSTtw0cVrCPHuNs6a9KCGt5fM9w8gzW28IsrNee9neKo0B57zl8q87fsNJ2ZpgCPLCM4D41nREvtM9tQnY5NSXJ688BHONwLvbxCZacRXtZZiwqOhWXlsgcjcFTbOhYqfzAZzr4GGT92XVadVyysxwLzEkq7nkAeR/V4nq0fZ6muixzQmlKc5zvW8Xt1Yai4c3LBU8qxlaFJtov6UZOGqaI4DcfxeBb4ZSh+rp63C9AGyJ4CmL5C+9kNFsA7ip9KoWqEzzCDnMAG2vjlLQlnKNi83p/KNueDxhxBQwLndfIbSlhgeywxhWyPOYZwM/QE71s9pgxxb9UG0Wsaq6x8K2x63b7u7iSDeyrce5lihdBSGJp7ziCGvPMjZ5MEc8GF1keY0GTW8WHJOIWb9B8H0lUSN5nF6P2ZvE0VN3EVf6JG7rDECzlsmAYDPYWZEfKgNjdvfjdIBNPxelhRO0Qu9EEeI3QA+byjYIE7XoCbH6wJcUCl3Q1pMsYq0pcNmkp0CFMHV4rVIwpWdKEBDmw1bSyI+2EEwIKzJZcPATit0SZYAIVpT10Wpe3JJXt8GkqN4TugH2JMSTXfMgid6DA4vDh4n3GOYbrZ/qc8Iwp+4L3mA//mCNzqpmIoUJZrV6iMajHD2c=
  - secure: haJ5O5SyRkOpFtbdRzGbr3L98XRenB9cz9mGHDhbHxUEUIWP7Mj3ENshBO+SmK6zDxh6/mIOT9F07ZI1nOBS7LBfmZ4QdS09ymFq8Gf0CyG28xBlmji9fea3A1zyQXv2SwBbuEa9AHrNLAsEt4SzsM1jf996mvouw1y64VtcxZWoEJ4VmIFjvuWXsOhmG8IRZHwSGh/slrSW8l1CW3BVLAox0IZtEOJaDYA33tAIJsiSC4JOTWZDi7gvJcciiPDy00wz8L5DrYynb9Rt9YJO+aVfvxu3Q0f7Q+Ia8RG/MUvrBtiZ1HpnVQvE3XtClrhj0SOti3lG7qHytfRzUjLQm7aivHYkNBoiFOlPXJ8NEaUycnwruOD6cggQq7J3SaGE/Zj4B0xdqpxZfAy1UZhnJtyjqq9FxnRhaLkGTxqR8aOcuSn00MMew2efUPyAKTWbfMrR9Dw4oFY3XwGFbIS/TGnAA5/XxDbU9Z9DMWaJZmBC/2LU4EYywItBiep7lY/HY7njX1Zc6cOs1kpbTdfhnjMbHKC4zCDA1ay8+Ye0+iOL7lYsiti3+wb4a+YiCKcAugnA9JPhZHgfMklXMMdB5mcoXyvhj7DvyTIs1bm2lEXMf8mSQyKNPG+WrCb5YbUlBVoOz1wL1BDCo3/FH8PVoAoC7+O3JmLpk99TQf1Wvt4=
cache:
  directories:
  - node_modules
before_deploy: npm run semantic-release pre
after_deploy: npm run semantic-release post
deploy:
  skip_cleanup: true
  provider: script
  script: npm publish
  on:
    repo: musicociel/cli
    branch: master
